ADCM-2118 Tests on immediate change of config, state and multistate
arenadata/adcm pull request #1124
Opened 2021-09-30 05:37 UTC by Sealwing

Tests on immediate change of config, state, and multi_state when running multijob

2021-09-30 06:11 UTC, skhomuti requested changes

2021-09-30 06:11 UTC, skhomuti commented on tests/functional/plugin_utils.py
> +        host = provider_host[1]
`_, host = provider_host`

2021-09-30 06:11 UTC, skhomuti approved these changes

2021-09-30 06:14 UTC, Sealwing commented on tests/functional/plugin_utils.py
> +        host = provider_host[1]
Yep, changed

2021-09-30 06:20 UTC, skhomuti approved these changes

2021-10-01 05:57 UTC, vgorkavenko approved these changes

2021-10-01 07:30 UTC, merged