Silent flaky tests for Firefox
arenadata/adcm pull request #1256
Opened 2021-11-10 10:52 UTC by Sealwing

2021-11-10 10:53 UTC, dgusakov requested changes

2021-11-10 10:53 UTC, dgusakov commented on tests/ui_tests/test_jobs_page.py
> +    @pytest.mark.usefixtures('skip_firefox')
Add a link to the fix issue

2021-11-10 11:00 UTC, Sealwing commented on tests/ui_tests/test_jobs_page.py
> +    @pytest.mark.usefixtures('skip_firefox')
Mentioned in TODOs

2021-11-10 11:15 UTC, dgusakov submitted a review, later dismissed

2021-11-11 06:44 UTC, dgusakov approved these changes

2021-11-11 09:07 UTC, merged