ADCM-2374_2 fix tests for tooltips and config fields
arenadata/adcm pull request #1342
Opened 2021-12-07 22:15 UTC by annademina

2021-12-08 05:44 UTC, skhomuti requested changes

2021-12-08 05:44 UTC, skhomuti commented on tests/ui_tests/app/page/common/base_page.py
> +    def scroll_to(self, locator: Union[Locator, WebElement]) -> WebElement:
it breaks config hell test

2021-12-08 06:54 UTC, annademina commented on tests/ui_tests/app/page/common/base_page.py
> +    def scroll_to(self, locator: Union[Locator, WebElement]) -> WebElement:
yep, fixed)

2021-12-08 11:40 UTC, skhomuti approved these changes

2021-12-09 06:43 UTC, alexterent approved these changes

2021-12-09 06:55 UTC, merged