ADCM-2465 make display_name unique only type=role roles
arenadata/adcm pull request #1397
Opened 2021-12-20 13:46 UTC by SofiaTal

2021-12-20 13:54 UTC, nagarin requested changes

2021-12-20 13:54 UTC, nagarin commented on python/rbac/endpoints/role/views.py
> +        try:
If Role.objects.get(display_name=display_name, type=RoleTypes.role).exists():
    raise ...
return display_name

2021-12-20 14:40 UTC, nagarin approved these changes

2021-12-23 06:18 UTC, acmnu commented
Why we need this? Do we have such requirements somewhere?

2021-12-24 06:04 UTC, nagarin approved these changes

2021-12-24 12:44 UTC, nagarin commented
bender build

2021-12-24 12:44 UTC, BenderArenadata commented
Hey, @nagarin! Build has been launched!

2021-12-28 11:36 UTC, merged