ADCM-2414 fix role name for component
arenadata/adcm pull request #1398
Opened 2021-12-20 13:49 UTC by SofiaTal

2021-12-20 14:39 UTC, nagarin approved these changes

2021-12-20 16:41 UTC, acmnu requested changes

2021-12-20 16:41 UTC, acmnu commented on python/cm/bundle.py
> +        if act.prototype.type == 'component':
@SofiaTal I don't like this. Lines 275-277 and 281-282 almost the same. So it is better to write difference to some variable and then compose result from the same template, but with small addition.

2021-12-21 11:55 UTC, acmnu approved these changes

2021-12-21 11:56 UTC, acmnu commented
bender build

2021-12-21 11:56 UTC, BenderArenadata commented
Hey, @acmnu! Build has been launched!

2021-12-21 14:01 UTC, merged