ADCM-2712 add actions and subactions for upgrade bundle
arenadata/adcm pull request #1665
Opened 2022-03-23 15:17 UTC by SofiaTal

2022-03-24 13:52 UTC, a-alferov requested changes

2022-03-24 15:45 UTC, SofiaTal commented on python/cm/stack.py
> +        return save_action(proto, conf, bundle_hash, conf['name'])
Done

2022-03-25 07:46 UTC, a-alferov commented on python/cm/stack.py
> +        return save_action(proto, conf, bundle_hash, conf['name'])
We need to process the upgrade name, I suggest like this `name = re.sub(r'\s+', '_', conf['name']).strip().lower()`

2022-03-28 12:28 UTC, a-alferov approved these changes

2022-03-28 12:29 UTC, merged