Adcm 2772
arenadata/adcm pull request #1706
Opened 2022-04-19 12:08 UTC by DanBalalan

2022-04-19 12:10 UTC, Sealwing requested changes

2022-04-19 12:10 UTC, Sealwing commented on tests/functional/test_multiple_adcm.py
>      hc_map = set_hc_map(cluster_to_export, provider)
please rebase on `ADCM-2072`, sync with the `develop` branch will come later)

2022-04-19 12:58 UTC, a-alferov commented on python/api/host/views.py
> +        if new_mode not in (MaintenanceModeType.On.value, MaintenanceModeType.Off.value):
Add pls check `disabled` value

2022-04-19 13:01 UTC, a-alferov commented on python/api/host/views.py
> +            partial=True,
I think because of this code `PUT` method will work like `PATCH`

2022-04-19 13:12 UTC, a-alferov commented on python/api/host/serializers.py
> +    maintenance_mode = serializers.ChoiceField(choices=MaintenanceModeType.choices, required=True)
I think `required=True` is redundant. We want this field not to be required when creating an object, but only required when updating

2022-04-21 11:23 UTC, a-alferov approved these changes

2022-04-21 11:25 UTC, merged