ADCM-2824 add string to check UI artefacts, make error_msg more clear
arenadata/adcm pull request #1756
Opened 2022-05-13 11:57 UTC by SofiaTal

2022-05-13 15:02 UTC, a-alferov requested changes

2022-05-13 15:02 UTC, a-alferov commented on python/api/group_config/serializers.py
> +                        raise AdcmEx('GROUP_CONFIG_CHANGE_UNSELECTED_FIELD', msg)
Add pls `log.info()`

2022-05-13 16:44 UTC, kuhella reviewed
Did you check this in attached data? 
Try to change any parameter (with active checkbox) and save it& is it ok?

2022-05-16 09:55 UTC, DanBalalan approved these changes

2022-05-16 11:28 UTC, a-alferov approved these changes

2022-05-16 11:29 UTC, SofiaTal commented
make build

2022-05-16 11:29 UTC, SofiaTal commented
bender build

2022-05-16 11:29 UTC, BenderArenadata commented
Hey, @SofiaTal! Build has been launched!

2022-05-16 12:24 UTC, merged