ADCM-2842 add filter for PrototypeList view
arenadata/adcm pull request #1777
Opened 2022-05-24 08:55 UTC by DanBalalan

2022-05-24 14:18 UTC, SofiaTal approved these changes

2022-05-27 08:28 UTC, a-alferov requested changes

2022-05-27 08:28 UTC, a-alferov commented on python/api/stack/filters.py
> +    type = drf_filters.CharFilter(label='type', field_name='type', lookup_expr='exact')
`bundle_id`, `type` unnecessarily, add this fields in `fields` field in `Meta` class

2022-05-27 08:28 UTC, a-alferov commented on python/api/stack/filters.py
> +    ordering = drf_filters.OrderingFilter(
`ordeting` unnecessarily, leave please `ordering_fields = ('display_name', 'version_order')` in view

2022-05-27 08:28 UTC, a-alferov commented on python/api/stack/views.py
> +    filter_backends = (filters.drf_filters.DjangoFilterBackend,)
this is unnecessarily, this is defined in the inherited class

2022-05-27 09:03 UTC, a-alferov approved these changes

2022-05-27 10:22 UTC, merged