ADCM-2731 add hostcomponentmap in cluster view
arenadata/adcm pull request #1779
Opened 2022-05-24 14:05 UTC by SofiaTal

2022-05-25 08:06 UTC, SofiaTal commented
bender build

2022-05-25 08:06 UTC, BenderArenadata commented
Hey, @SofiaTal! Build has been launched!

2022-05-25 11:06 UTC, SofiaTal commented
bender build

2022-05-25 11:06 UTC, BenderArenadata commented
Hey, @SofiaTal! Build has been launched!

2022-05-27 09:42 UTC, a-alferov requested changes

2022-05-27 09:42 UTC, a-alferov commented on python/api/serializers.py
> +        return {}
This should be a list `[]`

2022-05-30 16:27 UTC, SofiaTal commented on python/api/serializers.py
> +        return {}
Done in last commit

2022-05-30 16:40 UTC, a-alferov approved these changes

2022-05-30 16:41 UTC, merged