ADCM-2852 add logic for apply\revert host-component map for upgrade
arenadata/adcm pull request #1789
Opened 2022-05-30 16:25 UTC by SofiaTal

2022-05-31 10:34 UTC, a-alferov requested changes

2022-05-31 10:34 UTC, a-alferov commented on python/job_runner.py
> +    task.post_upgrade_hc_map = None
I think need add `task.save()`

2022-05-31 10:34 UTC, a-alferov commented on python/cm/job.py
> +    new_hc_list_of_tuple = api.check_hc(cluster, new_clear_hc)
Please think of a better name

2022-06-06 12:09 UTC, SofiaTal commented
bender build

2022-06-06 12:09 UTC, BenderArenadata commented
Hey, @SofiaTal! Build has been launched!

2022-06-08 09:14 UTC, a-alferov commented
bender build

2022-06-08 09:14 UTC, BenderArenadata commented
Hey, @a-alferov! Build has been launched!

2022-06-09 10:42 UTC, a-alferov approved these changes

2022-06-09 14:23 UTC, merged