Adcm-2936 add ui tests for ldap users and groups
arenadata/adcm pull request #1928
Opened 2022-07-29 10:29 UTC by annademina

2022-07-29 10:34 UTC, Sealwing requested changes

2022-07-29 10:34 UTC, Sealwing commented on tests/ui_tests/app/page/admin/page.py
> +                return group
raise exception (AssertionError) otherwise?

2022-07-29 10:34 UTC, Sealwing commented on tests/ui_tests/test_admin_page.py
> +    def test_change_ldap_user(self, users_page: AdminUsersPage, ldap_user_in_group):
change or check? I don't see change

2022-07-29 10:34 UTC, Sealwing commented on tests/ui_tests/test_admin_page.py
> +    def test_change_ldap_group(self, app_fs, ldap_user_in_group):
change or check? I don't see change

2022-07-29 10:43 UTC, annademina commented on tests/ui_tests/test_admin_page.py
> +    def test_change_ldap_group(self, app_fs, ldap_user_in_group):
changed to disabled

2022-07-29 10:43 UTC, annademina commented on tests/ui_tests/test_admin_page.py
> +    def test_change_ldap_user(self, users_page: AdminUsersPage, ldap_user_in_group):
changed to disabled

2022-07-29 10:43 UTC, annademina commented on tests/ui_tests/app/page/admin/page.py
> +                return group
yes, added

2022-07-29 11:09 UTC, Sealwing submitted a review, later dismissed

2022-07-29 13:03 UTC, kuhella reviewed
Need to add step  where ANY user might be added to local group according to https://tracker.yandex.ru/ADCM-3014

2022-08-02 08:37 UTC, Sealwing approved these changes

2022-08-03 08:15 UTC, merged