ADCM-3057 Add stdout logger
arenadata/adcm pull request #1965
Opened 2022-08-12 10:11 UTC by winmasta

2022-08-14 10:57 UTC, winmasta commented
Bender build

2022-08-14 10:57 UTC, BenderArenadata commented
Hey, @winmasta! Build has been launched!

2022-08-14 16:54 UTC, winmasta commented
Bender build

2022-08-14 16:54 UTC, BenderArenadata commented
Hey, @winmasta! Build has been launched!

2022-08-15 10:41 UTC, a-alferov requested changes

2022-08-15 10:41 UTC, a-alferov commented on os/etc/service/wsgi/run
> +uwsgi --venv "${adcmroot}/venv/default" --socket "${wsgisocketfile}" --pidfile "/run/uwsgi.pid" --module adcm.wsgi --chmod-socket=777
```suggestion
uwsgi --venv "${adcmroot}/venv/default" --socket "${wsgisocketfile}" --pidfile "/run/uwsgi.pid" --module adcm.wsgi --chmod-socket=777 --disable-logging
```
Add pls `--disable-logging` for disable UWSGI logs and show only Django logs

2022-08-16 02:38 UTC, winmasta commented
Bender build

2022-08-16 02:38 UTC, BenderArenadata commented
Hey, @winmasta! Build has been launched!

2022-08-16 07:35 UTC, winmasta commented
Bender build

2022-08-16 07:36 UTC, BenderArenadata commented
Hey, @winmasta! Build has been launched!

2022-08-16 13:54 UTC, a-alferov approved these changes

2022-08-16 14:21 UTC, merged