ADCM-3104 add checking of all structure key in case of group config
arenadata/adcm pull request #2008
Opened 2022-08-30 10:47 UTC by SofiaTal

2022-08-30 12:14 UTC, SofiaTal commented
bender build

2022-08-30 12:14 UTC, BenderArenadata commented
Hey, @SofiaTal! Build has been launched!

2022-08-31 13:42 UTC, winmasta requested changes

2022-08-31 13:42 UTC, winmasta commented on python/cm/adcm_config.py
> +        if spec[key + "/"].type != "group":
Ir's better to use f-interpolation if possible

2022-09-06 08:41 UTC, closed without merging