ADCM-3182 Download task log archive
arenadata/adcm pull request #2076
Opened 2022-09-15 10:51 UTC by winmasta

2022-09-15 15:00 UTC, winmasta commented
bender build

2022-09-15 15:00 UTC, BenderArenadata commented
Hey, @winmasta! Build has been launched!

2022-09-16 08:55 UTC, a-alferov requested changes

2022-09-16 08:55 UTC, a-alferov commented on python/api/job/views.py
> +                        f"{job.pk}-{dir_name_suffix}/ansible-{log_storage.type}.txt"
```suggestion
                        f"{job.pk}-{dir_name_suffix}/{log_storage.name}-{log_storage.type}.txt"
```

2022-09-16 08:55 UTC, a-alferov commented on python/cm/tests/files/task_log_download/1/ansible.json
> +{"ansible":  "json", "job_id": 1}
Pls rename files to `config.json`

2022-09-16 09:05 UTC, winmasta commented on python/api/job/views.py
> +                        f"{job.pk}-{dir_name_suffix}/ansible-{log_storage.type}.txt"
Fixed

2022-09-16 09:05 UTC, winmasta commented on python/cm/tests/files/task_log_download/1/ansible.json
> +{"ansible":  "json", "job_id": 1}
Fixed

2022-09-16 09:17 UTC, a-alferov approved these changes

2022-09-16 12:44 UTC, merged