ADCM-3196 Rework logging audit
arenadata/adcm pull request #2078
Opened 2022-09-15 15:22 UTC by DanBalalan

2022-09-16 09:14 UTC, a-alferov requested changes

2022-09-16 09:14 UTC, a-alferov commented on os/etc/service/wsgi/run
>  echo "Run main wsgi application ..."
lacks:
```bash
exec 1>>"${adcmlog}/service_wsgi.out"
exec 2>>"${adcmlog}/service_wsgi.err"
```

2022-09-16 09:24 UTC, DanBalalan commented on os/etc/service/wsgi/run
>  echo "Run main wsgi application ..."
added

2022-09-21 09:19 UTC, a-alferov approved these changes

2022-09-21 10:22 UTC, merged