ADCM-1451 'load_complete' the page event for automated tests
arenadata/adcm pull request #578
Opened 2020-09-28 15:29 UTC by DavidovPavel

2020-10-01 11:02 UTC, drKaramazin requested changes

2020-10-01 12:12 UTC, drKaramazin requested changes

2020-10-01 12:12 UTC, drKaramazin commented on web/src/app/app.component.ts
> +    this.radio.on<string>(keyChannelStrim.load_complete).subscribe(a => this.console(a, 'load_complete'));
for 'load_complete'

2020-10-01 12:12 UTC, drKaramazin commented on web/src/app/core/services/channel.service.ts
> +export enum keyChannelStrim {
cast the enum to a string enum https://www.typescriptlang.org/docs/handbook/enums.html#string-enums

2020-10-01 14:12 UTC, DavidovPavel commented on web/src/app/app.component.ts
> +    this.radio.on<string>(keyChannelStrim.load_complete).subscribe(a => this.console(a, 'load_complete'));
In this case, the 'load_complete' is a magic string with no keyChannelStream associated with it.
I can add that as constant, with comment

2020-10-02 11:05 UTC, acmnu approved these changes

2020-10-07 18:31 UTC, merged