ADCM-1394 fix(status) URL to request status
arenadata/adcm pull request #587
Opened 2020-10-06 14:27 UTC by DavidovPavel

2020-10-08 05:29 UTC, acmnu requested changes

2020-10-08 05:29 UTC, acmnu commented on web/package.json
> +    "start": "ng serve --proxyConfig=proxy.conf.json",
Is this a mistake?

2020-10-08 12:41 UTC, DavidovPavel commented on web/package.json
> +    "start": "ng serve --proxyConfig=proxy.conf.json",
No

2020-10-29 11:25 UTC, acmnu approved these changes

2020-10-29 13:51 UTC, merged