ADCM-1486 Added tests for upgrade object config
arenadata/adcm pull request #669
Opened 2020-12-14 12:59 UTC by a-alferov

2020-12-25 12:08 UTC, skhomuti requested changes

2020-12-25 12:08 UTC, skhomuti commented on python/cm/tests_upgrade.py
> +        self.assertTrue(False)
tests don't look complete

2020-12-25 13:40 UTC, a-alferov commented on python/cm/tests_upgrade.py
> +        self.assertTrue(False)
Yes, that is right

2021-03-18 09:18 UTC, grey-kristy approved these changes

2021-09-20 16:02 UTC, acmnu commented
Let's close it in favor to future better tests

2021-09-20 16:02 UTC, closed without merging