ADCM-1574 add test actions on old adcm versions
arenadata/adcm pull request #745
Opened 2021-02-11 08:22 UTC by skhomuti

2021-02-16 12:12 UTC, vgorkavenko approved these changes

2021-02-18 16:29 UTC, dgusakov requested changes

2021-02-18 16:29 UTC, dgusakov commented on go/Makefile
> +	cd $(ADCM); go mod download && go build -o ../bin/runstatus runstatus.go
revert this change

2021-02-19 05:10 UTC, skhomuti commented on go/Makefile
> +	cd $(ADCM); go mod download && go build -o ../bin/runstatus runstatus.go
done

2021-02-19 08:46 UTC, dgusakov approved these changes

2021-02-19 08:46 UTC, merged